gui-index:
    path: /
    controller: TechDivision\PspMock\Controller\Gui\IndexController::index
gui-order-list:
    path: /order/list/{type}
    controller: TechDivision\PspMock\Controller\Gui\OrderController::list
    requirements:
        type: '^[a-zA-Z]{0,}$'

help-index:
    path: /help/
    controller: TechDivision\PspMock\Controller\Help\IndexController::index

payone-server-api-post-gateway:
  path: /payone/post-gateway/
  defaults: { _controller: TechDivision\PspMock\Controller\Payone\ServerApi\PostGatewayController::execute }
  methods: [GET, POST]
payone-server-api-transactionstatus:
  path: /payone/server-api/transactionstatus/{order}/{action}
  defaults: { _controller: TechDivision\PspMock\Controller\Payone\ServerApi\TransactionStatusController::execute }
  methods: [GET]
payone-client-api:
  path: /payone/client-api/
  defaults: { _controller: TechDivision\PspMock\Controller\Payone\ClientApi\RequestController::execute }
payone-client-api-static:
  path: /payone/client-api/{req}
  defaults: { _controller: TechDivision\PspMock\Controller\Payone\ClientApi\StaticFileController::execute }
  requirements:
      req: ".+?"


heidelpay-payment-frame:
  path: /heidelpay/payment/frame
  controller: TechDivision\PspMock\Controller\Heidelpay\ClientApi\StaticFileController::execute
ngw/paymentFrame/sendData:
  path: /ngw/paymentFrame/sendData
  defaults: { _controller: TechDivision\PspMock\Controller\Heidelpay\ClientApi\FrameRequestController::execute }
  methods: [POST]
heidelpay-post:
  path: /ngw/post
  defaults: { _controller: TechDivision\PspMock\Controller\Heidelpay\ClientApi\RequestController:execute }
  methods: [POST]

settings-heidelpay-index:
  path: /settings/heidelpay
  controller: TechDivision\PspMock\Controller\Heidelpay\Settings\IndexController::index
settings-heidelpay-update:
  path: /settings/heidelpay/update
  controller: TechDivision\PspMock\Controller\Heidelpay\Settings\ConfigController::execute
  methods: [POST]
