index:
    path: /
    controller: TechDivision\PspMock\Controller\IndexController::index

payone-api:
  path: /payone/post-gateway/{req}
  defaults: { _controller: TechDivision\PspMock\Controller\Payone\PostGatewayController::execute }
  requirements:
      req: ".+?"

payone-client-api:
  path: /payone/client-api/
  defaults: { _controller: TechDivision\PspMock\Controller\Payone\ClientApi\RequestController::execute }
  requirements:
      req: ".+?"

payone-client-api-static:
  path: /payone/client-api/{req}
  defaults: { _controller: TechDivision\PspMock\Controller\Payone\ClientApi\StaticFileController::execute }
  requirements:
      req: ".+?"