index:
    path: /
    controller: TechDivision\PspMock\Controller\IndexController::index

payone-post-gateway:
  path: /payone/post-gateway/
  defaults: { _controller: TechDivision\PspMock\Controller\Payone\PostGatewayController::execute }
  methods: [GET, POST]

payone-client-api:
  path: /payone/client-api/
  defaults: { _controller: TechDivision\PspMock\Controller\Payone\ClientApi\RequestController::execute }

payone-client-api-static:
  path: /payone/client-api/{req}
  defaults: { _controller: TechDivision\PspMock\Controller\Payone\ClientApi\StaticFileController::execute }
  requirements:
      req: ".+?"